### ISSUE TITLE
ListInvoice parsing errors on invoices without `msatoshi` field

### ISSUE THREAD

**Issue by jonasnick** [laanwj/rust-clightning-rpc#17]
With `lightning-cli invoice "any" <label> <desc>` you can create an invoice that can be paid with any amount. Such invoices are shown with `listinvoices` without an `msatoshi` field. But apparently this field is expected by the `ListInvoice` struct, resulting in error `Json(missing field msatoshi)`.

**Comment by laanwj** [comment]
Ok, we should make that field optional then.

**Comment by mmilata** [comment]
This is addressed in #19.

**Comment by laanwj** [comment]
Fixed in version 0.2.0 (thanks to @mmilata)
