### ISSUE TITLE
Consider removing Arc<Mutex<>> from nonce

### ISSUE THREAD

**Issue by Kixunil** [laanwj/rust-clightning-rpc#4]
`Arc<Mutex<>>` adds synchronization even for clients that don't need it. The clients needing it can add that on their own.

Even if keeping this API is desired, using `AtomicUSize` is better than mutex (Unfortunately, `AtomicU64` is unstable now.)

**Comment by laanwj** [comment]
Strictly true, though the overhead of locking a mutex to increase the nonce is nothing compared to that of establishing a UNIX socket, serializing/unserializing JSON, and so on.

**Comment by laanwj** [comment]
I also think the nonce is nonsense as long as a new connection is opened for every request.

**Comment by sgeisler** [comment]
> I also think the nonce is nonsense as long as a new connection is opened for every request.

Since #15 removed the nonce altogether this issue seems to be resolved now.
