### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by laanwj** [laanwj/rust-clightning-rpc#8]
Some commands, such as `ping`, `fundchannel`, `waitanyinvoice`, have no built-in timeout and can seemingly hang forever.

It could be useful to be able to set a timeout, either for the entire connection (in the high-level API), or possibly per request (in the low-level API).

**Comment by Kixunil** [comment]
I fear that this would be quite complex to handle correctly without using `futures` and possibly `tokio`.

The main problem is that deadlines might be a better approach (if the server sends 1 byte with period `timeout-epsilon` the request might still take very long time). Although, assuming we are dealing with trusted server, we could drop some security requirements.

**Comment by laanwj** [comment]
> The main problem is that deadlines might be a better approach

With a timeout I mean a total maximum time for the request. E.g., "try to fund a channel, but stop after 10 minutes". So I suppose what you mean by a deadline.

> Although, assuming we are dealing with trusted server, we could drop some security requirements.

Yes, you can make that assumption, we're dealing with a local UNIX socket service here. It is not going to DoS you.

**Comment by laanwj** [comment]
I've implemented this in terms of `stream.set_read_timeout`/`stream.set_write_timeout` for now, works well enough for what I'm using it for (`ping` timeouts).
